import * as r from 'rethinkdb';
import * as cuid from 'cuid';
import { Canvas, HistoryEntry } from '../../../defs/canvas';

export class Connection {
    private conn: r.Connection;

    constructor(connection: r.Connection) {
        this.conn = connection;
    }

    getCanvas(id: string) {
        return r.table('canvases')
                    .get(id)
                    .run(this.conn);
    }

    getHistory(canvasID: string) {
        return r.table('history')
                    .getAll(canvasID, { index: 'canvasID' })
                    .orderBy('id')
                    .run(this.conn);
    }

    getHistoryFeed(canvasID: string) {
        return r.table('history')
                    .getAll(canvasID, { index: 'canvasID' })
                    .changes()
                    .run(this.conn);
    }

    addHistory(entry: HistoryEntry) {
        // Requires k-ordered ids, this eventually should be generated by
        // a separate service.
        entry.id = cuid();
        return r.table('history')
                    .insert([entry])
                    .run(this.conn);
    }
}

export function connect(options: r.ConnectionOptions) {
    return r.connect(options).then(conn => {
        return new Connection(conn);
    });
}