#!/usr/bin/env node
'use strict';

const r = require('rethinkdb');
const argv = require('minimist')(process.argv.slice(2));

const configFile = argv.config || '../packages/server/config/dev.config.json';
const config = require(configFile);

function printUsage() {
    console.log('usage: scripts/db [--config=file] <command>');
    console.log('available commands:');
    console.log('  help - Display this help text');
    console.log('  init - Initialize database');
    console.log('  clean - Clean up database entries');
}

function connect() {
    let connOptions = {
        host: config.db.host,
        port: config.db.port
    };
    if (config.db.authKey) {
        connOptions.authKey = config.db.authKey;
    }
    return r.connect(connOptions);
}

const commands = {
    help: async function() {
        printUsage();
    },
    init: async function() {
        let conn = await connect();
        conn.use(config.db.db);
        console.log('Creating database...');
        await r.dbCreate(config.db.db).run(conn);
        console.log('Creating tables...');
        await Promise.all([
            r.tableCreate('canvases').run(conn),
            r.tableCreate('history').run(conn),
            r.tableCreate('users', { primaryKey: 'username' }).run(conn)
        ]);
        console.log('Creating indexes...');
        await Promise.all([
            r.table('history').indexCreate('canvasID').run(conn),
            r.table('users').indexCreate('canvasID').run(conn)
        ]);
        console.log('Done.');
    },
    clean: async function() {
        let conn = await connect();
        conn.use(config.db.db);
        console.log('Cleaning database records...');
        await Promise.all([
            r.table('canvases').delete().run(conn),
            r.table('history').delete().run(conn),
            r.table('users').delete().run(conn)
        ]);
        console.log('Done');
    }
}

const command = argv._[0];
if (!command || !commands.hasOwnProperty(command)) {
    printUsage();
    process.exit();
}

commands[command]().then(() => {
    process.exit();
}).catch(error => {
    if (error.stack) {
        console.error(error.stack);
    } else {
        console.error(error);
    }
    process.exit();
});