#!/usr/bin/env node
'use strict';

const r = require('rethinkdb');
const argv = require('minimist')(process.argv.slice(2));
const config = require('../../config/server.json');

function printUsage() {
    console.log('usage: scripts/db help');
    console.log('       scripts/db configure');
    console.log('       scripts/db create <name>');
    console.log('       scripts/db clear <name>');
}

function connect() {
    let connOptions = {
        host: config.db.host,
        port: config.db.port
    };
    if (config.db.authKey) {
        connOptions.authKey = config.db.authKey;
    }
    return r.connect(connOptions);
}

const commands = {
    help: async function() {
        printUsage();
    },
    configure: async function() {
        let conn = await connect();
        conn.use(config.db.db);
        console.log('Creating database...');
        await r.dbCreate(config.db.db).run(conn);
        console.log('Creating tables...');
        await Promise.all([
            r.tableCreate('canvases').run(conn),
            r.tableCreate('history').run(conn)
        ]);
        console.log('Creating indexes...');
        await r.table('history').indexCreate('canvasID').run(conn);
        console.log('Done.');
    },
    create: async function() {
        let name = argv._[1];
        let conn = await connect();
        console.log(`Creating canvas "${name}"...`);
        conn.use(config.db.db);
        await r.table('canvases').insert([{
            id: name,
            width: 1200,
            height: 800,
            backgroundColor: '#ffffff'
        }]).run(conn);
        console.log('Done.');
    },
    clear: async function() {
        let id = argv._[1];
        let conn = await connect();
        conn.use(config.db.db);
        console.log(`Clearing canvas "${id}" history...`);
        await r.table('history').getAll(id, { index: 'canvasID' }).delete().run(conn);
        await r.table('canvases').get(id).update({ snapshot: '' }).run(conn);
        console.log('Done.');
    }
}

const command = argv._[0];
if (!command || !commands.hasOwnProperty(command)) {
    printUsage();
    process.exit();
}

commands[command]().then(() => {
    process.exit();
}).catch(error => {
    if (error.stack) {
        console.error(error.stack);
    } else {
        console.error(error);
    }
    process.exit();
});